server/iei/urls.py
from django.urls import path

from . import views

app_name = 'iei'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_task', views.create_task, name='create_task'),
    path('create_task_post', views.create_task_post, name='create_task_post'),
    path('get_waiting_task', views.get_waiting_task, name='get_waiting_task'),
    path('post_processed_task', views.post_processed_task, name='post_processed_task')
]

server/server/urls.py
from django.contrib import admin
from django.urls import include, path

from server.views import *

urlpatterns = [
    path('', index),
    path('iei/', include('iei.urls')),
    path("admin/", admin.site.urls),
]

server/iei/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Task(models.Model):
    class Status(models.TextChoices):
        WAITING = 'W', _('Waiting')
        PROCESSING = 'P', _('Processing')
        SUCCESSFUL = 'S', _('Successful')
        FAILED = 'F', _('Failed')

    task_id = models.BigAutoField(primary_key=True)
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.WAITING)
    time_created = models.DateTimeField('Time Created')
    time_finished = models.DateTimeField('Time Finished')
    payload = models.JSONField()

    def __str__(self):
        return f'Task #{self.task_id}'


class Image(models.Model):
    image_id = models.CharField(max_length=32, primary_key=True)
    task_id = models.BigIntegerField()

    def __str__(self):
        return f'Image #{self.task_id}_{self.image_id}'


class Prompt(models.Model):
    prompt = models.CharField(max_length=128)
    image_id = models.CharField(max_length=32)

    class Meta:
        indexes = [models.Index(fields=['prompt'])]

    def __str__(self):
        return self.prompt

server/iei/views.py
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from .models import Task, Image, Prompt

from .Payload import Payload

import json
from os import path, makedirs

outputs_dir = 'iei/static/iei/images/outputs'


def index(request):
    context = {'latest_tasks': []}
    for task in Task.objects.filter(time_created__lte=timezone.now()).order_by('-time_created')[:5]:
        task_info = {'task_id': task.task_id, 'status': Task.Status(task.status).label, 'images': []}
        if task.status == Task.Status.SUCCESSFUL:
            for image in Image.objects.filter(task_id=task.task_id):
                task_info['images'].append(
                    {'image_id': image.image_id, 'image_url': f'iei/images/outputs/{image.image_id}.png'})

        context['latest_tasks'].append(task_info)

    return render(request, 'iei/index.html', context)


def create_task(request):
    return render(request, 'iei/create_task.html')


def create_task_post(request):
    payload = Payload(
        prompt=request.POST.get('prompt'),
        negative_prompt=request.POST.get('negative_prompt'),
        steps=int(request.POST.get('steps')),
        sampler_name=request.POST.get('sampler_name'),
        width=int(request.POST.get('width')),
        height=int(request.POST.get('height')),
        restore_faces=bool(request.POST.get('restore_faces')),
        tiling=bool(request.POST.get('tiling')),
        enable_hr=bool(request.POST.get('enable_hr')),
        firstphase_width=int(request.POST.get('firstphase_width')),
        firstphase_height=int(request.POST.get('firstphase_height')),
        denoising_strength=float(request.POST.get('denoising_strength')),
        n_iter=int(request.POST.get('n_iter')),
        batch_size=int(request.POST.get('batch_size')),
        cfg_scale=float(request.POST.get('cfg_scale')),
        seed=int(request.POST.get('seed')),
        subseed=int(request.POST.get('subseed')),
        subseed_strength=float(request.POST.get('subseed_strength')),
        seed_resize_from_w=int(request.POST.get('seed_resize_from_w')),
        seed_resize_from_h=int(request.POST.get('seed_resize_from_h')),
        eta=float(request.POST.get('eta')),
        s_churn=float(request.POST.get('s_churn')),
        s_tmin=float(request.POST.get('s_tmin')),
        s_noise=float(request.POST.get('s_noise'))
    )

    Task.objects.create(
        status=Task.Status.WAITING,
        time_created=timezone.now(),
        time_finished=timezone.now(),
        payload=payload.__dict__
    )

    return HttpResponseRedirect(reverse('iei:index'))


def get_waiting_task(request):
    response = '{"task_id": -1, "payload": {}}'
    with transaction.atomic():
        task = Task.objects.filter(status=Task.Status.WAITING).order_by('time_created')[:1]
        if task:
            task = task[0]
            response = f'{{"task_id": {task.task_id}, "payload": {json.dumps(task.payload)}}}'
            task.status = Task.Status.PROCESSING
            task.save()

    return HttpResponse(response)


@csrf_exempt
def post_processed_task(request):
    if not path.exists(outputs_dir):
        makedirs(outputs_dir)

    task_id = request.POST['task_id']
    status = Task.Status(request.POST['status'])
    error_massage = ''

    if status == Task.Status.SUCCESSFUL:
        images = request.POST['images'].split('\n')
        for file_name in images:
            image_data = request.FILES.get(file_name)
            if not image_data:
                status = Task.Status.FAILED
                error_massage = f'Task #{task_id} without image: {file_name}'
                break
    else:
        error_massage = request.POST['error']

    # Failed
    if status == Task.Status.FAILED:
        task = Task.objects.get(task_id=task_id)
        task.status = Task.Status.FAILED
        task.time_finished = timezone.now()
        task.save()
        return HttpResponse(f'post_processed_task FAILED: {error_massage}')

    # Successful
    task = Task.objects.get(task_id=task_id)
    images = request.POST['images'].split('\n')
    for file_name in images:
        image_id = file_name.split('.')[0]
        Image.objects.create(image_id=image_id, task_id=task_id)
        for prompt in task.payload['prompt'].split(','):
            Prompt.objects.create(prompt=prompt.strip(' ()'), image_id=image_id)

        image_data = request.FILES.get(file_name)
        with open(f'{outputs_dir}/{file_name}', 'wb+') as file:
            for chunk in image_data.chunks():
                file.write(chunk)

    task.status = Task.Status.SUCCESSFUL
    task.time_finished = timezone.now()
    task.save()

    return HttpResponse(
        f'post_processed_task accomplished: ' +
        f'Task #{task_id} with {len(images)} image{"s" if len(images) > 1 else ""}: \n' +
        request.POST['images'])

server/server/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

server/iei/templates/iei/create_task.html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <title>Create a task</title>
</head>
<body>
<h1>Create a task</h1>
<form action="{% url 'iei:create_task_post' %}" method="post">
    {% csrf_token %}

    <input type="submit" value="提交">

    <h2>咒语</h2>

    <label for="prompt">Prompt:</label>
    <input id="prompt" type="text" name="prompt" value="cute, girl, blue sky"><br><br>

    <label for="negative_prompt">Negative prompt:</label>
    <input id="negative_prompt" type="text" name="negative_prompt"><br><br>

    <h2>采样</h2>

    <label for="steps">Sampling Steps:</label>
    <input id="steps" type="number" min="1" max="150" name="steps" value="20"><br><br>

    <label for="sampler_name">Sampling method:</label>
    <select id="sampler_name" name="sampler_name">
        <option value="Euler a" selected="selected">Euler a</option>
        <option value="Euler">Euler</option>
        <option value="LMS">LMS</option>
        <option value="Heun">Heun</option>
        <option value="DPM2">DPM2</option>
        <option value="DPM2 a">DPM2 a</option>
        <option value="DPM++ 2S a">DPM++ 2S a</option>
        <option value="DPM++ 2M">DPM++ 2M</option>
        <option value="DPM++ SDE">DPM++ SDE</option>
        <option value="DPM fast">DPM fast</option>
        <option value="DPM adaptive">DPM adaptive</option>
        <option value="LMS Karras">LMS Karras</option>
        <option value="DPM2 Karras">DPM2 Karras</option>
        <option value="DPM2 a Karras">DPM2 a Karras</option>
        <option value="DPM++ 2S a Karras">DPM++ 2S a Karras</option>
        <option value="DPM++ 2M Karras">DPM++ 2M Karras</option>
        <option value="DPM++ SDE Karras">DPM++ SDE Karras</option>
        <option value="DDIM">DDIM</option>
        <option value="PLMS">PLMS</option>
    </select><br><br>

    <h2>大小</h2>

    <label for="width">Width:</label>
    <input id="width" type="number" min="1" max="1024" name="width" value="512"><br><br>

    <label for="height">Height:</label>
    <input id="height" type="number" min="1" max="1024" name="height" value="384"><br><br>

    <h2>任务</h2>

    <label for="n_iter">Batch count:</label>
    <input id="n_iter" type="number" min="1" max="100" name="n_iter" value="2"><br><br>

    <label for="batch_size">Batch size:</label>
    <input id="batch_size" type="number" min="1" max="8" name="batch_size" value="4"><br><br>

    <h2>优化</h2>

    <label for="restore_faces">Restore faces:</label>
    <input id="restore_faces" type="checkbox" name="restore_faces"><br><br>

    <label for="tiling">Tiling:</label>
    <input id="tiling" type="checkbox" name="tiling"><br><br>

    <h3>高对比度修复</h3>

    <label for="enable_hr">Highres. fix:</label>
    <input id="enable_hr" type="checkbox" name="enable_hr"><br><br>

    <label for="firstphase_width">Firstpass width:</label>
    <input id="firstphase_width" type="number" min="0" max="1024" name="firstphase_width" value="0"><br><br>

    <label for="firstphase_height">Firstpass height:</label>
    <input id="firstphase_height" type="number" min="0" max="1024" name="firstphase_height" value="0"><br><br>

    <label for="denoising_strength">Denoising strength:</label>
    <input id="denoising_strength" type="number" min="0.0" max="1.0" step="0.01" name="denoising_strength"
           value="0.7"><br><br>

    <h2>随机性</h2>

    <label for="cfg_scale">CFG Scale:</label>
    <input id="cfg_scale" type="number" min="1.0" max="30.0" step="0.5" name="cfg_scale" value="7.0"><br><br>

    <label for="seed">Seed:</label>
    <input id="seed" type="number" name="seed" value="-1"><br><br>

    <label for="subseed">Variation seed:</label>
    <input id="subseed" type="number" name="subseed" value="-1"><br><br>

    <label for="subseed_strength">Variation strength:</label>
    <input id="subseed_strength" type="number" min="0.0" max="1.0" step="0.01" name="subseed_strength"
           value="0.0"><br><br>

    <label for="seed_resize_from_w">Resize seed from width:</label>
    <input id="seed_resize_from_w" type="number" min="0" max="2048" name="seed_resize_from_w" value="0"><br><br>

    <label for="seed_resize_from_h">Resize seed from height:</label>
    <input id="seed_resize_from_h" type="number" min="0" max="2048" name="seed_resize_from_h" value="0"><br><br>

    <h2>其它</h2>

    <label for="eta">eta (noise multiplier) for DDIM:</label>
    <input id="eta" type="number" min="0.0" max="1.0" step="0.01" name="eta" value="0.0"><br><br>

    <label for="s_churn">sigma churn:</label>
    <input id="s_churn" type="number" min="0.0" max="1.0" step="0.01" name="s_churn" value="0.0"><br><br>

    <label for="s_tmin">sigma tmin:</label>
    <input id="s_tmin" type="number" min="0.0" max="1.0" step="0.01" name="s_tmin" value="0.0"><br><br>

    <label for="s_noise">sigma noise:</label>
    <input id="s_noise" type="number" min="0.0" max="1.0" step="0.01" name="s_noise" value="1.0"><br><br>
</form>
</body>
</html>

server/iei/templates/iei/index.html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <title>Intelligent Ecstatic Illustrator</title>
    {% load static %}
</head>
<body>
<h1>Intelligent Ecstatic Illustrator</h1>
<a href="{% url 'iei:create_task' %}">Create a task</a>

{% if latest_tasks %}
    {% for task in latest_tasks %}
        <h2>Task #{{ task.task_id }} - {{ task.status }}</h2>
        {% if task.images %}
            <ul>
                {% for image in task.images %}
                    <li><img alt="{{ image.image_id }}" src="{% static image.image_url %}" width="512" height="384"></li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endfor %}

{% else %}
    <p>No tasks are available.</p>
{% endif %}
</body>
</html>

server/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hoshizora</title>
</head>
<body>
<h1>Hoshizora</h1>
<h2>Intelligent Ecstatic Illustrator</h2>
<a href="iei/">IEI</a>
</body>
</html>